/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.cloud.agentplatform.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.auto.value.AutoValue;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.genai.JsonSerializable;
import com.google.genai.types.HttpOptions;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.Optional;

/** Config for ingesting events. */
@AutoValue
@JsonDeserialize(builder = IngestEventsConfig.Builder.class)
public abstract class IngestEventsConfig extends JsonSerializable {
  /** Used to override HTTP request options. */
  @JsonProperty("httpOptions")
  public abstract Optional<HttpOptions> httpOptions();

  /**
   * Waits for the underlying memory generation operation to complete before returning. Defaults to
   * false.
   */
  @JsonProperty("waitForCompletion")
  public abstract Optional<Boolean> waitForCompletion();

  /**
   * Optional. Forces a flush of all pending events in the stream and triggers memory generation
   * immediately bypassing any conditions configured in the `generation_trigger_config`.
   */
  @JsonProperty("forceFlush")
  public abstract Optional<Boolean> forceFlush();

  /**
   * Labels to apply to the memory revision. For example, you can use this to label a revision with
   * its data source.
   */
  @JsonProperty("revisionLabels")
  public abstract Optional<Map<String, String>> revisionLabels();

  /**
   * Optional. Input only. Timestamp of when the revision is considered expired. If not set, the
   * memory revision will be kept until manually deleted.
   */
  @JsonProperty("revisionExpireTime")
  public abstract Optional<Instant> revisionExpireTime();

  /** Optional. Input only. The TTL for the revision. The expiration time is computed: now + TTL. */
  @JsonProperty("revisionTtl")
  public abstract Optional<Duration> revisionTtl();

  /** Optional. Input only. If true, no revisions will be created for this request. */
  @JsonProperty("disableMemoryRevisions")
  public abstract Optional<Boolean> disableMemoryRevisions();

  /**
   * Optional. User-provided metadata for the generated memories. This is not generated by Memory
   * Bank.
   */
  @JsonProperty("metadata")
  public abstract Optional<Map<String, MemoryMetadataValue>> metadata();

  /** Optional. The strategy to use when applying metadata to existing memories. */
  @JsonProperty("metadataMergeStrategy")
  public abstract Optional<MemoryMetadataMergeStrategy> metadataMergeStrategy();

  /** Instantiates a builder for IngestEventsConfig. */
  @ExcludeFromGeneratedCoverageReport
  public static Builder builder() {
    return new AutoValue_IngestEventsConfig.Builder();
  }

  /** Creates a builder with the same values as this instance. */
  public abstract Builder toBuilder();

  /** Builder for IngestEventsConfig. */
  @AutoValue.Builder
  public abstract static class Builder {
    /** For internal usage. Please use `IngestEventsConfig.builder()` for instantiation. */
    @JsonCreator
    private static Builder create() {
      return new AutoValue_IngestEventsConfig.Builder();
    }

    /**
     * Setter for httpOptions.
     *
     * <p>httpOptions: Used to override HTTP request options.
     */
    @JsonProperty("httpOptions")
    public abstract Builder httpOptions(HttpOptions httpOptions);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder httpOptions(Optional<HttpOptions> httpOptions);

    /** Clears the value of httpOptions field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearHttpOptions() {
      return httpOptions(Optional.empty());
    }

    /**
     * Setter for waitForCompletion.
     *
     * <p>waitForCompletion: Waits for the underlying memory generation operation to complete before
     * returning. Defaults to false.
     */
    @JsonProperty("waitForCompletion")
    public abstract Builder waitForCompletion(boolean waitForCompletion);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder waitForCompletion(Optional<Boolean> waitForCompletion);

    /** Clears the value of waitForCompletion field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearWaitForCompletion() {
      return waitForCompletion(Optional.empty());
    }

    /**
     * Setter for forceFlush.
     *
     * <p>forceFlush: Optional. Forces a flush of all pending events in the stream and triggers
     * memory generation immediately bypassing any conditions configured in the
     * `generation_trigger_config`.
     */
    @JsonProperty("forceFlush")
    public abstract Builder forceFlush(boolean forceFlush);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder forceFlush(Optional<Boolean> forceFlush);

    /** Clears the value of forceFlush field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearForceFlush() {
      return forceFlush(Optional.empty());
    }

    /**
     * Setter for revisionLabels.
     *
     * <p>revisionLabels: Labels to apply to the memory revision. For example, you can use this to
     * label a revision with its data source.
     */
    @JsonProperty("revisionLabels")
    public abstract Builder revisionLabels(Map<String, String> revisionLabels);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder revisionLabels(Optional<Map<String, String>> revisionLabels);

    /** Clears the value of revisionLabels field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearRevisionLabels() {
      return revisionLabels(Optional.empty());
    }

    /**
     * Setter for revisionExpireTime.
     *
     * <p>revisionExpireTime: Optional. Input only. Timestamp of when the revision is considered
     * expired. If not set, the memory revision will be kept until manually deleted.
     */
    @JsonProperty("revisionExpireTime")
    public abstract Builder revisionExpireTime(Instant revisionExpireTime);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder revisionExpireTime(Optional<Instant> revisionExpireTime);

    /** Clears the value of revisionExpireTime field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearRevisionExpireTime() {
      return revisionExpireTime(Optional.empty());
    }

    /**
     * Setter for revisionTtl.
     *
     * <p>revisionTtl: Optional. Input only. The TTL for the revision. The expiration time is
     * computed: now + TTL.
     */
    @JsonProperty("revisionTtl")
    public abstract Builder revisionTtl(Duration revisionTtl);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder revisionTtl(Optional<Duration> revisionTtl);

    /** Clears the value of revisionTtl field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearRevisionTtl() {
      return revisionTtl(Optional.empty());
    }

    /**
     * Setter for disableMemoryRevisions.
     *
     * <p>disableMemoryRevisions: Optional. Input only. If true, no revisions will be created for
     * this request.
     */
    @JsonProperty("disableMemoryRevisions")
    public abstract Builder disableMemoryRevisions(boolean disableMemoryRevisions);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder disableMemoryRevisions(Optional<Boolean> disableMemoryRevisions);

    /** Clears the value of disableMemoryRevisions field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearDisableMemoryRevisions() {
      return disableMemoryRevisions(Optional.empty());
    }

    /**
     * Setter for metadata.
     *
     * <p>metadata: Optional. User-provided metadata for the generated memories. This is not
     * generated by Memory Bank.
     */
    @JsonProperty("metadata")
    public abstract Builder metadata(Map<String, MemoryMetadataValue> metadata);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder metadata(Optional<Map<String, MemoryMetadataValue>> metadata);

    /** Clears the value of metadata field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearMetadata() {
      return metadata(Optional.empty());
    }

    /**
     * Setter for metadataMergeStrategy.
     *
     * <p>metadataMergeStrategy: Optional. The strategy to use when applying metadata to existing
     * memories.
     */
    @JsonProperty("metadataMergeStrategy")
    public abstract Builder metadataMergeStrategy(
        MemoryMetadataMergeStrategy metadataMergeStrategy);

    @ExcludeFromGeneratedCoverageReport
    abstract Builder metadataMergeStrategy(
        Optional<MemoryMetadataMergeStrategy> metadataMergeStrategy);

    /** Clears the value of metadataMergeStrategy field. */
    @ExcludeFromGeneratedCoverageReport
    @CanIgnoreReturnValue
    public Builder clearMetadataMergeStrategy() {
      return metadataMergeStrategy(Optional.empty());
    }

    /**
     * Setter for metadataMergeStrategy given a known enum.
     *
     * <p>metadataMergeStrategy: Optional. The strategy to use when applying metadata to existing
     * memories.
     */
    @CanIgnoreReturnValue
    public Builder metadataMergeStrategy(MemoryMetadataMergeStrategy.Known knownType) {
      return metadataMergeStrategy(new MemoryMetadataMergeStrategy(knownType));
    }

    /**
     * Setter for metadataMergeStrategy given a string.
     *
     * <p>metadataMergeStrategy: Optional. The strategy to use when applying metadata to existing
     * memories.
     */
    @CanIgnoreReturnValue
    public Builder metadataMergeStrategy(String metadataMergeStrategy) {
      return metadataMergeStrategy(new MemoryMetadataMergeStrategy(metadataMergeStrategy));
    }

    public abstract IngestEventsConfig build();
  }

  /** Deserializes a JSON string to a IngestEventsConfig object. */
  @ExcludeFromGeneratedCoverageReport
  public static IngestEventsConfig fromJson(String jsonString) {
    return JsonSerializable.fromJsonString(jsonString, IngestEventsConfig.class);
  }
}
